# Generated by Django 4.2.6 on 2023-12-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='subject',
            new_name='content',
        ),
    ]
