# Generated by Django 4.2.6 on 2023-12-19 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_posts_likes_count_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
