# Generated by Django 4.2.6 on 2023-12-20 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_posts_followings_alter_posts_likes_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='followings',
        ),
        migrations.CreateModel(
            name='Followings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followings', models.ManyToManyField(blank=True, null=True, related_name='followings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_is_following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
